# Generated by Django 4.2.1 on 2023-06-01 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('label', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthDate',
            field=models.DateField(auto_now=True),
        ),
    ]
